apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    deployed.by: REDACTED
    app: grafana-deployment
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: grafana-pod
  template:
    metadata:
      labels:
        app: grafana-pod
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      containers:
        - name: grafana
          image: grafana/grafana:XXXX
          ports:
            - containerPort: 3000
              name: https-grafana
              protocol: TCP
          volumeMounts:
            - name: ldapconfig
              mountPath: /etc/grafana/ldap.toml
              subPath: ldap.toml
            - name: grafanaini
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: grafanads
              mountPath: /etc/grafana/provisioning/datasources
          env:
          - name: GF_INSTALL_PLUGINS
            value: redis-datasource
          - name: LDAP_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana
                key:  LDAP_ADMIN_PASSWORD
          - name: ADMUSER
            valueFrom:
              secretKeyRef:
                name: grafana
                key:  ADMUSER
          - name: ADMPASS
            valueFrom:
              secretKeyRef:
                name: grafana
                key:  ADMPASS
          - name: MAILPASS
            valueFrom:
              secretKeyRef:
                name: grafana
                key:  MAILPASS
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: grafana
                key:  DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: grafana
                key:  DB_PASS
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: grafana
                key: CLIENT_ID
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: grafana
                key: CLIENT_SECRET
          resources:
            limits:
              memory: 300Mi
              cpu:  400m
            requests:
              cpu: 250m
              memory: 150Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
      volumes:
        - name: ldapconfig
          configMap:
            name: grafana-ldap
        - name: grafanaini
          configMap:
            name: grafana-ini
        - name: grafanads
          configMap:
            name: grafana-ds