apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
      REDACTED: REDACTED
      THIS_ONE: REDACTED
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
    type: Opaque

